### ISSUE TITLE
OrangeFox link broken.

### ISSUE THREAD

**Issue by thatsitipl** [droidian-mt6765/kernel-xiaomi-mt6765#1]
Just for clarification : i know this isn't the device-page repository but all of the other repos are forked and i am only able to create an issue here.

The OrangeFox link on the droidian device page for dandelion/angelica seems broken and it isn't archived anywhere else.
The link: https://garden.bardia.tech/OrangeFox-R11-garden-droidian.img

Best Regards.

Edit: The same is true for the PBRP recovery.

**Comment by FakeShell** [comment]
fixed 
thanks
