### ISSUE TITLE
Dandelion Touchscreen driver

### ISSUE THREAD

**Issue by thatsitipl** [droidian-mt6765/kernel-xiaomi-mt6765#2]
Where are the touchscreen drivers for dandelion located? Or better which touchscreen does it use.

**Comment by FakeShell** [comment]
many different touch screen drivers are included in the kernel
some are missing because of XIAOMI not updating their crap

**Comment by thatsitipl** [comment]
Closing since fix already proposed in adaption

**Comment by JeyKul** [comment]
@thatsitipl wild
